[tool.poetry]
name = "car-game"
version = "0.1.0"
description = ""
authors = ["Muhammadzulqarnainhaider <zh576198@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
